# Generated by Django 2.0.5 on 2019-08-08 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chname', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('basicPrice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(default=None, upload_to='images')),
                ('img3', models.ImageField(default=None, upload_to='images')),
                ('img4', models.ImageField(default=None, upload_to='images')),
                ('img5', models.ImageField(default=None, upload_to='images')),
                ('img6', models.ImageField(default=None, upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(default=None, on_delete='CASCADE', to='App.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='App.Size'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_product',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='App.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
