# Generated by Django 2.0.5 on 2019-08-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_checkout_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkid',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
    ]
