# Generated by Django 2.0.5 on 2019-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordernumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
