# Generated by Django 2.0.5 on 2019-08-14 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0006_order_ordernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('order_address', models.ForeignKey(default=None, on_delete='CASCADE', to='App.Checkout')),
                ('order_product', models.ForeignKey(default=None, on_delete='CASCADE', to='App.Product')),
                ('order_user', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
